name: Lint and Test Code

on:
    pull_request:
        branches-ignore: [gh-pages]
    push:
        branches-ignore: [gh-pages]

jobs:
    lint_and_test_code:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7
            - uses: pnpm/action-setup@v6
              with:
                  run_install: false

            - name: Setup Node
              uses: actions/setup-node@v7
              with:
                  node-version: "24"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint
              run: pnpm lint || (echo && echo "Run 'pnpm format' to fix." && exit 1)

            - name: Test
              run: pnpm test
 
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0 
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}

            - name: Upload results for analytics
              uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./junit.xml
                  report_type: test_results
